using PuppeteerSharp;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Mvc.Abstractions;
using BreachApi.ViewModels;
using Microsoft.Extensions.Logging;

namespace BreachApi.Services;

/// <summary>
/// Service for PDF generation using PuppeteerSharp and Razor views
/// </summary>
public class PdfService : IPdfService
{
    private readonly ICompositeViewEngine _viewEngine;
    private readonly ITempDataProvider _tempDataProvider;
    private readonly IServiceProvider _serviceProvider;
    private readonly ILogger<PdfService> _logger;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public PdfService(
        ICompositeViewEngine viewEngine,
        ITempDataProvider tempDataProvider,
        IServiceProvider serviceProvider,
        ILogger<PdfService> logger,
        IHttpContextAccessor httpContextAccessor)
    {
        _viewEngine = viewEngine;
        _tempDataProvider = tempDataProvider;
        _serviceProvider = serviceProvider;
        _logger = logger;
        _httpContextAccessor = httpContextAccessor;
    }

    /// <summary>
    /// Generates a PDF report from the provided view model
    /// </summary>
    /// <param name="viewModel">The view model containing breach data</param>
    /// <returns>PDF file as byte array</returns>
    public async Task<byte[]> GenerateBreachReportPdfAsync(BreachReportViewModel viewModel)
    {
        _logger.LogInformation("Generating PDF report for {BreachCount} breaches with date range: {DateRange}", 
            viewModel.TotalBreaches, viewModel.DateRangeDisplay);

        try
        {
            // Generate HTML content using Razor view
            var htmlContent = await GenerateHtmlContentAsync(viewModel);
            
            // Generate PDF using PuppeteerSharp
            var pdfBytes = await GeneratePdfFromHtmlAsync(htmlContent);
            
            _logger.LogInformation("Successfully generated PDF report. Size: {PdfSize} bytes", pdfBytes.Length);
            
            return pdfBytes;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating PDF report");
            throw new InvalidOperationException("Failed to generate PDF report", ex);
        }
    }

    /// <summary>
    /// Generates PDF from HTML content using PuppeteerSharp
    /// </summary>
    /// <param name="htmlContent">The HTML content to convert</param>
    /// <returns>PDF file as byte array</returns>
    private async Task<byte[]> GeneratePdfFromHtmlAsync(string htmlContent)
    {
        // Download Chromium if not already installed
        await new BrowserFetcher().DownloadAsync();

        using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
        {
            Headless = true,
            Args = new[] { "--no-sandbox", "--disable-setuid-sandbox" }
        });

        using var page = await browser.NewPageAsync();

        // Set content and wait for network idle
        await page.SetContentAsync(htmlContent, new NavigationOptions
        {
            WaitUntil = new[] { WaitUntilNavigation.Networkidle0 }
        });

        // Configure PDF options
        var pdfOptions = new PdfOptions
        {
            PrintBackground = true,
            DisplayHeaderFooter = true,
            HeaderTemplate = "<div style='font-size: 10px; text-align: right; width: 100%; margin-right: 20px;'>Page <span class='pageNumber'></span> of <span class='totalPages'></span></div>",
            FooterTemplate = "<div style='font-size: 10px; text-align: center; width: 100%;'>Breach Report generated by Breach API</div>"
        };

        // Generate PDF
        var pdfBytes = await page.PdfDataAsync(pdfOptions);
        return pdfBytes;
    }

    /// <summary>
    /// Generates HTML content using Razor view engine
    /// </summary>
    /// <param name="viewModel">The view model</param>
    /// <returns>HTML content as string</returns>
    private async Task<string> GenerateHtmlContentAsync(BreachReportViewModel viewModel)
    {
        var viewName = "BreachReport";
        var viewData = new ViewDataDictionary<BreachReportViewModel>(new EmptyModelMetadataProvider(), new ModelStateDictionary())
        {
            Model = viewModel
        };

        // Create a valid HttpContext and ActionContext
        var httpContext = _httpContextAccessor.HttpContext ?? new DefaultHttpContext { RequestServices = _serviceProvider };
        var actionContext = new ActionContext(httpContext, new RouteData(), new ActionDescriptor());

        var tempData = new TempDataDictionary(httpContext, _tempDataProvider);

        using var stringWriter = new StringWriter();
        var viewResult = _viewEngine.FindView(actionContext, viewName, false);

        if (!viewResult.Success)
        {
            throw new InvalidOperationException($"View '{viewName}' not found");
        }

        var viewContext = new ViewContext(
            actionContext,
            viewResult.View,
            viewData,
            tempData,
            stringWriter,
            new HtmlHelperOptions());

        await viewResult.View.RenderAsync(viewContext);
        return stringWriter.ToString();
    }
} 